"""
Pydantic models used by the MediAssist AI API.

These classes define the request and response schemas for the
endpoints exposed by the backend.  By centralizing models in this
module, both the FastAPI application and any clients (such as
Streamlit) can import a single source of truth for validation.
"""

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class AskReportRequest(BaseModel):
    """Request body for the /ask-report endpoint.

    Attributes:
        report_text: The full text extracted from a previously analyzed
            report.  This allows the LLM to answer questions in
            context without redoing OCR.
        question: The user's question about the report.  This can be in
            either English or Bangla.
        language: The preferred answer language; either ``"English"`` or
            ``"Bangla"``.  Defaults to ``"English"`` if omitted.
    """

    report_text: str = Field(..., description="Extracted report text")
    question: str = Field(..., description="User question about the report")
    language: Optional[str] = Field(default="English", description="Desired answer language")


class DetectedParameter(BaseModel):
    """Represents a single detected lab value from a medical report.

    Attributes:
        name: Name of the laboratory test (e.g. ``"Hemoglobin"``).
        value: The numeric value found in the report (as a string to
            preserve formatting).
        reference_range: The reference range found in the report.
        status: A simple status describing whether the value appears to
            be ``"low"``, ``"normal"``, or ``"high"`` relative to the
            reference range.
    """

    name: str
    value: str
    reference_range: str
    status: str


class AnalyzeReportResponse(BaseModel):
    """Response body for the /analyze-report endpoint.

    Attributes:
        status: Indicates success or failure.  Typically ``"success"``.
        language: The language used for the explanation.
        raw_text: Raw OCR output prior to parsing.
        summary: A one or two sentence summary of the report.
        abnormal_items: List of detected abnormal values, if any.
        explanation: The full explanation text returned from the LLM.
        disclaimer: Safety disclaimer text appended to every response.
    """

    status: str
    language: str
    raw_text: str
    summary: str
    abnormal_items: List[DetectedParameter]
    explanation: str
    disclaimer: str


class AskReportResponse(BaseModel):
    """Response body for the /ask-report endpoint.

    Attributes:
        status: Indicates success or failure.
        answer: The answer generated by the LLM given the report text
            and the user's question.
    """

    status: str
    answer: str
